//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParseErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParseErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFiles.ParseErrorMessages", typeof(ParseErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid limits should be integers and greater than 0..
        /// </summary>
        public static string GridCoordinatesBadFormat {
            get {
                return ResourceManager.GetString("GridCoordinatesBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid coordinates should be greater than 0 with a maximun value of 50..
        /// </summary>
        public static string GridCoordinatesShoudBeBetween0_50 {
            get {
                return ResourceManager.GetString("GridCoordinatesShoudBeBetween0_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid coordinates should be 2 integers separated by a white space..
        /// </summary>
        public static string GridCoordinatesWrongElementsNumber {
            get {
                return ResourceManager.GetString("GridCoordinatesWrongElementsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximun of 100 instrucciones can be processed..
        /// </summary>
        public static string InstructionsNumberGreaterThanMaximum {
            get {
                return ResourceManager.GetString("InstructionsNumberGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not any instruction to be processed..
        /// </summary>
        public static string InstructionsNumberIsNull {
            get {
                return ResourceManager.GetString("InstructionsNumberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are invalid characteres in instructions line. Line is discarded..
        /// </summary>
        public static string InstructionsSetWithInvalidInstructionInput {
            get {
                return ResourceManager.GetString("InstructionsSetWithInvalidInstructionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Position coordinates should be integers and greater than 0..
        /// </summary>
        public static string RobotPositionCoordinatesBadFormat {
            get {
                return ResourceManager.GetString("RobotPositionCoordinatesBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Position Coordinates should be in the grid limits..
        /// </summary>
        public static string RobotPositionInputOutOfGrid {
            get {
                return ResourceManager.GetString("RobotPositionInputOutOfGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Position coordinates should be greater than 0 with a maximun value of 50..
        /// </summary>
        public static string RobotPositionInputShoudBeBetween0_50 {
            get {
                return ResourceManager.GetString("RobotPositionInputShoudBeBetween0_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Position input should be composed by 3 elements separated by a white space..
        /// </summary>
        public static string RobotPositionInputWrongElementsNumber {
            get {
                return ResourceManager.GetString("RobotPositionInputWrongElementsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot orientation input is not a valid orientation..
        /// </summary>
        public static string RobotPositionOrientationInputWrongFormat {
            get {
                return ResourceManager.GetString("RobotPositionOrientationInputWrongFormat", resourceCulture);
            }
        }
    }
}
