//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UITexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourceFiles.UITexts", typeof(UITexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Grid Input.
        /// </summary>
        public static string ConfirmGridInput {
            get {
                return ResourceManager.GetString("ConfirmGridInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Position Input.
        /// </summary>
        public static string ConfirmPositionInput {
            get {
                return ResourceManager.GetString("ConfirmPositionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Output.
        /// </summary>
        public static string ConfirmProcessOutput {
            get {
                return ResourceManager.GetString("ConfirmProcessOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Robot Input.
        /// </summary>
        public static string ConfirmRobotInput {
            get {
                return ResourceManager.GetString("ConfirmRobotInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string ErrorMessageHeader {
            get {
                return ResourceManager.GetString("ErrorMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Position.
        /// </summary>
        public static string FinalPositionHeader {
            get {
                return ResourceManager.GetString("FinalPositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string ForwardInstruction {
            get {
                return ResourceManager.GetString("ForwardInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Coordinates.
        /// </summary>
        public static string GridCoordinatesData {
            get {
                return ResourceManager.GetString("GridCoordinatesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. X.
        /// </summary>
        public static string GridMaxX {
            get {
                return ResourceManager.GetString("GridMaxX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Y.
        /// </summary>
        public static string GridMaxY {
            get {
                return ResourceManager.GetString("GridMaxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Size.
        /// </summary>
        public static string GridSize {
            get {
                return ResourceManager.GetString("GridSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUTS.
        /// </summary>
        public static string InputsData {
            get {
                return ResourceManager.GetString("InputsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string InstructionsHeader {
            get {
                return ResourceManager.GetString("InstructionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions Sequence.
        /// </summary>
        public static string InstructionsSequenceInput {
            get {
                return ResourceManager.GetString("InstructionsSequenceInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction Type.
        /// </summary>
        public static string InstructionTypeInput {
            get {
                return ResourceManager.GetString("InstructionTypeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string LeftInstruction {
            get {
                return ResourceManager.GetString("LeftInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG MESSAGES.
        /// </summary>
        public static string LogMessagesData {
            get {
                return ResourceManager.GetString("LogMessagesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string OrientationInput {
            get {
                return ResourceManager.GetString("OrientationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Position.
        /// </summary>
        public static string OriginalPositionHeader {
            get {
                return ResourceManager.GetString("OriginalPositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUTPUTS.
        /// </summary>
        public static string OutputsData {
            get {
                return ResourceManager.GetString("OutputsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string RestartConfirmation {
            get {
                return ResourceManager.GetString("RestartConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string RightInstruction {
            get {
                return ResourceManager.GetString("RightInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot.
        /// </summary>
        public static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot ID.
        /// </summary>
        public static string RobotIdHeader {
            get {
                return ResourceManager.GetString("RobotIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Inputs.
        /// </summary>
        public static string RobotInputs {
            get {
                return ResourceManager.GetString("RobotInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robot Position .
        /// </summary>
        public static string RobotPositionInput {
            get {
                return ResourceManager.GetString("RobotPositionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Coord.
        /// </summary>
        public static string XCoordinateData {
            get {
                return ResourceManager.GetString("XCoordinateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X pos.
        /// </summary>
        public static string XPosInput {
            get {
                return ResourceManager.GetString("XPosInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Coord.
        /// </summary>
        public static string YCoordinateData {
            get {
                return ResourceManager.GetString("YCoordinateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y pos.
        /// </summary>
        public static string YPosInput {
            get {
                return ResourceManager.GetString("YPosInput", resourceCulture);
            }
        }
    }
}
